name: Deploy

on:
  push:
    tags: ['[0-9]+.[0-9]+*']

env:
  SDK_VERSION: ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Twine and dependencies
        run: pip install twine requests==2.* requests-toolbelt==0.* appengine-python-standard
      - name: Build
        run: python setup.py sdist --formats gztar --dist-dir .
      - name: Rename for PEP 625 compatibility
        # Twine may or may not already correct the filename; only rename if the non-compatible filename exists
        run: if [ -f "connect-sdk-python3-${SDK_VERSION}.tar.gz" ]; then mv "connect-sdk-python3-${SDK_VERSION}.tar.gz" "connect_sdk_python3-${SDK_VERSION}.tar.gz"; fi
      - name: Verify
        run: twine check "connect_sdk_python3-${SDK_VERSION}.tar.gz"
      - name: Deploy
        run: twine upload --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" "connect_sdk_python3-${SDK_VERSION}.tar.gz"
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
