name: Deploy

on:
  push:
    tags: ['[0-9]+.[0-9]+*']

env:
  SDK_VERSION: ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Twine and dependencies
        run: pip install twine requests==2.* requests-toolbelt==0.* appengine-python-standard
      - name: Build
        run: python setup.py sdist --formats gztar --dist-dir .
      - name: Rename for PEP 625 compatibility
        # Twine may or may not already correct the filename; only rename if the non-compatible filename exists
        run: if [ -f "connect-sdk-python3-${SDK_VERSION}.tar.gz" ]; then mv "connect-sdk-python3-${SDK_VERSION}.tar.gz" "connect_sdk_python3-${SDK_VERSION}.tar.gz"; fi
      - name: Verify
        run: twine check "connect_sdk_python3-${SDK_VERSION}.tar.gz"
      - name: Deploy
        run: |
          # retrieve the ambient OIDC token
          resp=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=pypi")
          oidc_token=$(jq -r '.value' <<< "${resp}")

          # exchange the OIDC token for an API token
          resp=$(curl -X POST https://pypi.org/_/oidc/mint-token -d "{\"token\": \"${oidc_token}\"}")
          api_token=$(jq -r '.token' <<< "${resp}")

          # mask the newly minted API token, so that we don't accidentally leak it
          echo "::add-mask::${api_token}"

          TWINE_USERNAME=__token__ TWINE_PASSWORD=${api_token} twine upload "connect_sdk_python3-${SDK_VERSION}.tar.gz"
